/**
 * Daily pre-generated horoscope loader.
 * Fetches data/daily-horoscope.json (generated by cron) and serves
 * bilingual (zh/en) text per sign. Pure frontend, no router/build deps.
 */
const DailyHoro = (() => {
  'use strict';

  const SIGN_KEYS = [
    'aries','taurus','gemini','cancer','leo','virgo',
    'libra','scorpio','sagittarius','capricorn','aquarius','pisces'
  ];

  let _cache = null;

  async function _load() {
    if (_cache) return _cache;
    try {
      const resp = await fetch('./data/daily-horoscope.json');
      if (!resp.ok) return null;
      _cache = await resp.json();
      return _cache;
    } catch {
      return null;
    }
  }

  function _isFresh(data) {
    if (!data || !data.date) return false;
    var d = new Date();
    var y = d.getFullYear();
    var m = String(d.getMonth() + 1).padStart(2, '0');
    var day = String(d.getDate()).padStart(2, '0');
    return data.date === y + '-' + m + '-' + day;
  }

  return {
    /** @return {Promise<string|null>} horoscope text in requested language */
    async getDaily(signIndex, lang) {
      var data = await _load();
      if (!data || !_isFresh(data)) return null;
      var key = SIGN_KEYS[signIndex];
      if (!key || !data.horoscopes || !data.horoscopes[key]) return null;
      var entry = data.horoscopes[key];
      return lang === 'zh' ? (entry.zh || null) : (entry.en || null);
    },

    /** Check whether cached data is from today. Useful for UI hints. */
    isFresh() {
      return _cache ? _isFresh(_cache) : false;
    }
  };
})();
